### PR TITLE
Add ability to use manager with proxy

### PR DESCRIPTION
**Pull request by rosolko**
Play with a code a little bit and create alternative solution. 
Can you please review it?
Is is satisfactory solution for you?

Closes #88

### CODE REVIEW

**Comment by rosolko** [comment]
@geforce-hisa0904 ping!

**Comment by geforce-hisa0904** [comment]
Hi  @rosolko 
Thank you for considering on my behalf.
Your modification is smarter! I would like you to apply this modification.

---
I modified only the default value of Proxy. Please refer to it if you like.
I think it's a little cleaner to create instance the WebClient.
https://github.com/geforce-hisa0904/WebDriverManager.Net/commit/dca7bf87958c1ecdd4e42b1c2a330cdc91c1ecf7

**Comment by rosolko** [comment]
@geforce-hisa0904 As I understood using `DefaultWebProxy` assume that you're going to use `default` proxy any way (and it's not equals to `no proxy`), by in my solution you have an ability to completely ignore proxy.

**Comment by geforce-hisa0904** [comment]
@rosolko Your implementation behaves the same as my modification. I thought it would be a little easier to see, so I commented as above.
Thank you for Proxy support! I will use it!

**Pull request merged**
